version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  nest:
    build: .
    ports:
      - "3000:3000"
    links:
      - db:db